chore: #148 upgrade examples
MindscapeHQ/raygun4node pull request #157
Opened 2024-04-24 10:02 UTC by miquelbeltran

## chore: #148 upgrade examples

### Description :memo:

Take the two examples in the repo and upgrade dependencies. Also ensure that they use the `raygun4node` found in the repo, not the one from `npm`.

**Type of change**

- [x] Tech debt ;)

**Updates**

- Upgrade dependencies in `examples/express-sample`.
- Upgrade dependencies in `examples/using-domains`.
- Ensure both examples use the `raygun` node package from the repo, not the one hosted in `npm`.
- Adds multiple `console.log` to `examples/using-domains`.
- Fixes indentation in `examples/using-domains/app.js`.

TODO: Once https://github.com/MindscapeHQ/raygun4node/pull/156 is merged, I want to include the example projects in the lint checks.

### Test plan :test_tube:

- Run both examples.

### Author to check :eyeglasses:
- [x] Project and all contained modules builds successfully
- [x] Self-/dev-tested 
- [x] Unit/UI/Automation/Integration tests provided where applicable
- [x] Code is written to standards
- [x] Appropriate documentation written (code comments, internal docs)

### Reviewer to check :heavy_check_mark:
- [ ] Project and all contained modules builds successfully
- [ ] Change has been dev-/reviewer-tested, where possible
- [ ] Unit/UI/Automation/Integration tests provided where applicable
- [ ] Code is written to standards
- [ ] Appropriate documentation written (code comments, internal docs)

2024-04-24 10:03 UTC, miquelbeltran commented on examples/express-sample/package.json
> +    "raygun": "file:../..",
`raygun` dependency points to the one at the repo root, instead of using an outdated one from `npm`.

2024-04-25 22:35 UTC, TheRealAgentK reviewed
LGTM overall, haven't built/tested it myself yet though. Will do later and then approve/merge the PR.

2024-04-25 23:27 UTC, sumitramanga reviewed
Code also looks good to me! I'll look to spin this up for testing and follow the instructions

2024-04-26 01:32 UTC, sumitramanga commented on examples/express-sample/package.json
It would be awesome to have the README more filled in on how to run the example apps!

I didn't realise we had to build the provider first before building and running the app! This tripped me up badly as I was wondering why TS was needed in the example app as the example app didn't have TS but the provider itself does. Went down a rabbit hold 😬 But realised the situation as mentioned before.

2024-04-26 01:33 UTC, sumitramanga commented on examples/express-sample/package.json
I think we just need to add in "ensure you've built the provider in the root directory before running this example app". Same goes for the other example app

2024-04-26 01:41 UTC, sumitramanga commented on examples/express-sample/package.json
Do we need to explicitly point out the API Key change to ensure that the config value is changed to their API Key? Just to make it obvious to the user

2024-04-26 01:42 UTC, sumitramanga requested changes
Just one small change that people would benefit having IMO :) 

Otherwise, testing went well and the apps are working with error being piped into Raygun 🙌

2024-04-26 01:45 UTC, sumitramanga reviewed
Oh, one other issue I did have with the express example app was that I had to run `set DEBUG=express-sample:server && node ./bin/www` instead of  `npm start` to get the server up and running. Not sure why, but the server just terminates when running `npm start` so the other option that worked was the manual run in terminal. 

Let me know how you guys get on with `npm start` @miquelbeltran @TheRealAgentK ? It could just be a local issue on my end perhaps...

2024-04-26 05:38 UTC, miquelbeltran commented
> I didn't realise we had to build the provider first before building and running the app!

I've added that step now to the README

> Do we need to explicitly point out the API Key change to ensure that the config value is changed to their API Key? Just to make it obvious to the user

I can add that check on the examples, or even in the package itself, that if the key == `YOUR_API_KEY` then it should warn the user.

> Not sure why, but the server just terminates when running npm start so the other option that worked was the manual run in terminal.

I did not have this issue, that's strange...

2024-04-28 22:13 UTC, sumitramanga commented
Thank you for addressing those @miquelbeltran !
As for the local set up issues, I don't think this is tied to provider issues themselves but a problem on my computer. So no need to add additional information around how I addressed the problem

2024-04-28 22:13 UTC, sumitramanga approved these changes
LGTM! 🎸

2024-04-29 05:33 UTC, merged