chore: Release 0.15.0 🚀
MindscapeHQ/raygun4node pull request #201
Opened 2024-05-07 22:18 UTC by sumitramanga

## [chore]: Release 0.15.0 🚀

### Description :memo:
- **Purpose**: We are releasing version 0.15.0 of the provider
- **Approach**: Merge all changes in `develop` into `master`

**Type of change**
- [x] Release

**Release contents**
:point_right: Add support to async/await to `send` API method
:point_right: Fix avoiding infinite recursion in` filterKeys` method
:point_right: Various documentation and workflow changes
:point_right: Dev dependency updates 

### Test plan :test_tube:
- Run example apps and ensure that test exceptions are sending to Raygun
- Run the provider on clean project locally
- Use the `send` method in the example apps and clean project

### Author to check :eyeglasses:
- [ ] Project and all contained modules builds successfully
- [ ] Self-/dev-tested 
- [ ] Unit/UI/Automation/Integration tests provided where applicable
- [ ] Code is written to standards
- [ ] Appropriate documentation written (code comments, internal docs)

### Reviewer to check :heavy_check_mark:
- [ ] Project and all contained modules builds successfully
- [ ] Change has been dev-/reviewer-tested, where possible
- [ ] Unit/UI/Automation/Integration tests provided where applicable
- [ ] Code is written to standards
- [ ] Appropriate documentation written (code comments, internal docs)

2024-05-07 22:20 UTC, sumitramanga commented
Hi @paul-uz, we've managed to push foward with getting a release ready for your requested Issue  https://github.com/MindscapeHQ/raygun4node/pull/181

We should have this out soon!

2024-05-08 05:23 UTC, miquelbeltran requested changes
Something seems wrong about this PR, merging `develop` into `master` again shouldn't show all these changes. I think this is due to the rebasing of `master`. Probably this can be fixed by merging `master` into `develop` first with a merge commit, otherwise commit history has diverged.

Secondly, the release process should be done in a two-step process:

1st. We need to increase the version in the `package.json` and update the CHANGELOG, on a separated PR into `develop`. This is necessary so the version change is found on both branches.

2nd. We do the merge of `develop` into `master` effectively doing the release merge.

This is something that git-flow would solve for us as well.

I'd recommend closing this PR and follow those steps.

2024-05-08 05:40 UTC, miquelbeltran commented
The version preparing PR is here: https://github.com/MindscapeHQ/raygun4node/pull/202

2024-05-08 05:45 UTC, miquelbeltran commented
We can keep this PR open, I will fix the diverged history between master and develop in a new PR meanwhile.

2024-05-08 05:54 UTC, miquelbeltran commented
And the PR fixing the merge conflicts: https://github.com/MindscapeHQ/raygun4node/pull/203

2024-05-08 07:33 UTC, paul-uz commented
I'm confused, is the latest version 0.14.0 or 0.15.0?

2024-05-08 07:35 UTC, miquelbeltran commented
> I'm confused, is the latest version 0.14.0 or 0.15.0?

0.14.0 has been just released, and we are preparing 0.15.0-0 with the async/await change

2024-05-08 07:37 UTC, miquelbeltran commented
well, the PR I did actually doesn't fix the merge conflicts

2024-05-08 08:11 UTC, miquelbeltran approved these changes
LGTM, tested locally with both examples

2024-05-08 08:12 UTC, miquelbeltran commented
remember, we need to do a "Merge pull request" ;)

2024-05-08 08:23 UTC, sumitramanga commented
@miquelbeltran Will do, thank you for the reminder!

2024-05-08 22:08 UTC, PanosNB requested changes
All good, great work! One things to consider please around cycle prevention and not deleting ancestor references from the set. We could also add the case of two or more backwards references to the test (great to see that there!)

2024-05-09 00:37 UTC, sumitramanga reviewed
I can't approve my own PR but this looks good to me! Panos raises a good point so that's something to look into

2024-05-09 01:58 UTC, PanosNB approved these changes
All good, I had misunderstood smth before. Great work!

2024-05-09 01:58 UTC, PanosNB commented on lib/raygun.messageBuilder.ts
> +      delete _obj[key];
My bad, looking back into this, I see now that we do not delete the _explored set. All good, I will approve

2024-05-09 06:02 UTC, TheRealAgentK approved these changes
Ok, LGTM! Let's release it.

2024-05-09 06:04 UTC, merged

2024-05-09 11:57 UTC, paul-uz commented
Can I ask why this is marked as `0.15.0-0` and not just `0.15.0`? It means I can no longer use `^0.15.0` in my package file

2024-05-09 20:46 UTC, miquelbeltran commented
Hi @paul-uz, we have released the async/await send method support as pre-release (that's why the `-0` at the end) to collect feedback from users. Once we are sure it works as expected, we will do a proper stable release.

In the near future, the Raygun team plans to do a proper `1.0.0` eventually, nevertheless.